spring:
  application:
    name: api-gateway-service

  redis:
    host: localhost
    port: 6379

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        #user service
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1

        #transaction service
        - id: transaction-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/transactions/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1

        #reward service
        - id: reward-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/rewards/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1

        ##notification service
        - id: notification-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/notify/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1

logging:
  level:
    com:
      paypal:
        api_gateway:
          filters : INFO

  httpclient:
    max-initial-line-length: 4096
    max-header-size: 8192
    filters:
      - name: RequestSize
        args:
          maxSize: 1MB

server:
  port : 8080
